---
name: Release
on:
  push:
    tags:
      - "v*"

env:
  KIND_VERSION: "v0.33.0"
  KIND_IMAGE: "kindest/node:v1.36.4@sha256:099e049362a1526b2db71494e1947aae99bd16290d7c895f2b7ea312e3cbfaed"

jobs:
  release:
    name: Release
    runs-on: ubuntu-26.04
    permissions:
      contents: write
      packages: write
    steps:
      - name: Free disk space
        run: |
          sudo rm -rf /usr/share/dotnet
          sudo rm -rf /usr/local/lib/android
          sudo rm -rf /opt/ghc
          sudo rm -rf /usr/local/.ghcup
          sudo rm -rf /usr/local/share/boost
          sudo rm -rf /opt/hostedtoolcache/CodeQL
          sudo docker image prune --all --force > /dev/null
          df -h

      - name: Checkout code
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1  # v7.0.1
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@b7ad1dad31e06c5925ef5d2fc7ad053ef454303e  # v7.0.0
        with:
          go-version-file: go.mod

      - name: Run unit tests
        run: make tests

      - name: Setup Kubernetes cluster (KIND)
        uses: engineerd/setup-kind@ecfad61750951586a9ef973db567df1d28671bdc  # v0.6.2
        with:
          version: ${{ env.KIND_VERSION }}
          image: ${{ env.KIND_IMAGE }}
          name: kube-bench

      - name: Test connection to Kubernetes cluster
        run: |
          kubectl cluster-info
          kubectl describe node

      - name: Run integration tests
        run: |
          make integration-test

      - name: Compare output with expected output
        uses: GuillaumeFalourd/diff-action@b341507d1da990caceac1b3b31b8f55eebaa2e99  # v1
        with:
          first_file_path: ./test.data
          second_file_path: integration/testdata/Expected_output.data
          expected_result: PASSED

      - name: Release
        uses: goreleaser/goreleaser-action@f06c13b6b1a9625abc9e6e439d9c05a8f2190e94  # v7.2.3
        with:
          distribution: goreleaser
          version: v1.7.0
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
